image: node:11.10.1

stages:
    - deploy

before_script:
  - apt-get update -qq && apt-get install
  - apt-get install -y lftp
  - yarn install

deploy:
  stage: deploy
  script:
    - yarn build
    - lftp -d -e "set ftp:ssl-allow  no; open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST; mirror -Rev public/ ./_sub/blog  --ignore-time --parallel=10 --exclude-glob .git* --exclude .git/"
