image: ubuntu:18.04

stages:
  deploy

before_script:
  - apt-get update -qy
  - apt-get install -y lftp

deploy:
  state: deploy
  script:
    - lftp -e "open $FTP_HOST; user $FTP_USERNAME $FTP_PASSWORD; mirror -X .* -X .*/ --reverse --verbose --delete local-folder/ destination-folder/; bye"
  only:
    - master
