image: ubuntu:18.04

# stages:
#   deploy

before_script:
  - apt-get update -qy
  - apt-get install -y lftp

compile_assets:
  stage: build
  script:
    - yarn install --pure-lockfile --cache-folder .yarn-cache
    - yarn build

deploy:
#   stage: deploy
#     # only:
#     #     - master
  script:
    - apt-get update -qq && apt-get install -y -qq lftp
#     # - lftp -c "set ftp:ssl-allow no; open -u $FTP_PASSWORD, $FTP_PASSWORD $FTP_HOST; mirror -Rev public/ ./_sub/blog  --ignore-time --parallel=10 --exclude-glob .git* --exclude .git/"
