image: ubuntu:18.04

stages:
    - compile_assets
    - deploy

before_script:
  - apt-get update -qy
  - apt-get install -y lftp
  - apt-get install yarn -y

compile_assets:
  script:
    - yarn install
    - yarn build

deploy:
  script:
    - lftp -c "open -u $FTP_USERNAME $FTP_PASSWORD sftp://$FTP_HOST; mirror -Rev public/ ./_sub/blog  --ignore-time --parallel=10 --exclude-glob .git* --exclude .git/"


